### ISSUE TITLE
"Error: Error: command failed"

### ISSUE THREAD

**Issue by Mennaruuk** [maykbrito/yt-trimmer#1]
**Sample URL: https://www.youtube.com/watch?v=p86ZOmxiTx4**

```
Lenovo:yt-trimmer lenovo$ node index.js
Youtube url: https://www.youtube.com/watch?v=p86ZOmxiTx4
Video starts in (00:00:00.00): 00:00:00.01
Video ends in (00:00:00.00): 00:00:10.00
Nome do arquivo: (padrao: part.mp4): 
> Starting dowload and convert
===================================
start (00:00:00.01) - end (00:00:10.00): toSeconds: 10
Error waiting for robots:

  Error: Error: Command failed: ffmpeg -ss 00:00:00.01 -i "https://r5---sn-vgqsrnee.googlevideo.com/videoplayback?expire=1604900886&ei=toOoX--zHKGN2_gPssih-Ak&ip=2601%3A410%3A4301%3Ae2b0%3A2046%3A58f4%3A1b5%3Ae0f2&id=o-ABeVz7HyvVyxTz4vSlKcSAFjrE28RpVWaRtXa-CdxZn3&itag=22&source=youtube&requiressl=yes&mh=RR&mm=31%2C26&mn=sn-vgqsrnee%2Csn-p5qs7ned&ms=au%2Conr&mv=m&mvi=5&pl=26&initcwndbps=2075000&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=308.337&lmt=1604859520453096&mt=1604879199&fvip=5&c=WEB&txp=3416222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKOmTZtanq3wB0ntbZ7ICUq9XjI7sscXRcUwpkhjT1DcAiEAqRcvFNv5an4aRiVpT53O9G1EkEfDNzeQz7OHY7zuvwk%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgUl8YfL79d3CW9tUARHsiyGKpY5_KLAEMH92PwFYxAFACIEzI4ZAbVraazgyZzwMBGfwfbLdYBXppIhobDV2T98In" -t 10.-1 -c copy part.mp4
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

    at downloadPart (/Users/Lenovo/Documents/yt-trimmer/robots/trim.js:34:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.module.exports [as trim] (/Users/Lenovo/Documents/yt-trimmer/robots/trim.js:40:5)
    at async start (/Users/Lenovo/Documents/yt-trimmer/index.js:7:5)
```

**Comment by maykbrito** [comment]
Thanks for your feedback @Mennaruuk 

It's fixed!
