### ISSUE TITLE
python not found? WTF?

### ISSUE THREAD

**Issue by dura0ok** [maykbrito/yt-trimmer#2]
Mint 20.1
node 14, npm 6.14

npm start

> yt-trimmer@1.0.1 start /home/stepan7/projects/yt-trimmer
> node src/index.js

Youtube url: https://youtu.be/zcKuJOYAxSs
Video starts in (00:00:00.00): 00:24:08.03                            
Video ends in (00:00:00.00): 00:24:38.03
Nome do arquivo: (padrao: part.mp4): 
Error waiting for robots:

  Error: Command failed: sh ./scripts/videourl.sh https://youtu.be/zcKuJOYAxSs
/usr/bin/env: «python»: Нет такого файла или каталога

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'sh ./scripts/videourl.sh https://youtu.be/zcKuJOYAxSs',
  stdout: '',
  stderr: '/usr/bin/env: «python»: Нет такого файла или каталога\n'
}

**Comment by maykbrito** [comment]
I think that it's caused by some Youtube-dl's dependency.
