### ISSUE TITLE
'sh' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by mohamedsalem401** [maykbrito/yt-trimmer#3]
Error: Command failed: sh ./scripts/videourl.sh https://www.youtube.com/watch?v=XjAxqeAMEo8
'sh' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'sh ./scripts/videourl.sh https://www.youtube.com/watch?v=XjAxqeAMEo8',
  stdout: '',
  stderr: "'sh' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n'
}

**Comment by maykbrito** [comment]
The `sh` was removed from this project.
