### ISSUE TITLE
Video unavailable

### ISSUE THREAD

**Issue by LuisanSuarez** [maykbrito/yt-trimmer#6]
Hey! Thanks so much for sharing this project. Been looking for a solution for over an hour and was about to start pulling my hair out.

The video does not load on Chrome/Brave browser. works fine with `npm run trimall`. I tried the default video, and my own. No luck.

https://www.youtube.com/watch?v=gBmnB7BwSRA
<img width="576" alt="image" src="https://github.com/user-attachments/assets/fe3f6b55-8141-42ff-a43d-cb26410974cd">

I used pnpm install and bun dev.

**Comment by cassiohenriqueofc** [comment]
I had the same issue. I´ve installed using "npm install", open the video on the browser and selected the in and out using the respective buttons on UI. When I hit "Download", the applocation show error like this one:

```
> yt-trimmer@1.0.3 trimall
> node src/actions/multiple-parts.js

===================================
start (00:01:19) - end (00:01:40): toSeconds: 21, ms: 0
> Dowloading and converting
===================================
start (00:04:30) - end (00:05:00): toSeconds: 30, ms: 0
> Dowloading and converting
Error waiting for robots:

  Error: Error: Command failed: ffmpeg -ss 00:01:19       -i "$(yt-dlp -f 'bestvideo[height<=1080]+bestaudio[height<=1080]/best' -g 'https://www.youtube.com/watch?v=gBmnB7BwSRA')"       -t 21.0       -c:a aac -c:v libx264 -preset ultrafast       -s 1920x1080       part-0.mp4
ffmpeg version 8.0-full_build-www.gyan.dev Copyright (c) 2000-2025 the FFmpeg developers
  built with gcc 15.2.0 (Rev8, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-lcms2 --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-libdvdnav --enable-libdvdread --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-liboapv --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-openal --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-liblc3 --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint --enable-whisper
  libavutil      60.  8.100 / 60.  8.100
  libavcodec     62. 11.100 / 62. 11.100
  libavformat    62.  3.100 / 62.  3.100
  libavdevice    62.  1.100 / 62.  1.100
  libavfilter    11.  4.100 / 11.  4.100
  libswscale      9.  1.100 /  9.  1.100
  libswresample   6.  1.100 /  6.  1.100
[in#0 @ 000001fc84325640] Error opening input: Invalid argument
Error opening input file $(yt-dlp -f 'bestvideo[height<=1080]+bestaudio[height<=1080]/best' -g 'https://www.youtube.com/watch?v=gBmnB7BwSRA').
Error opening input files: Invalid argument

    at Object.downloadPart [as download] (G:\Applications\youtube-trim\src\robots\download.js:47:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async G:\Applications\youtube-trim\src\actions\multiple-parts.js:23:9
    at async Promise.all (index 0)
    at async G:\Applications\youtube-trim\src\actions\multiple-parts.js:15:5
```
